/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;
//import java.util.*;

import com.mycompany.campeonatocarreras.Pasajero;
import com.mycompany.campeonatocarreras.Horario;
import com.mycompany.campeonatocarreras.Participante;

/**
 *
 * @author Gabriel
 */
public class PantallParticipante extends javax.swing.JFrame {

    Pasajero pasajeros[] = new Pasajero[4];
    Horario horarios[] = new Horario[3];
    Participante participantes[] = new Participante[10];
    
    public PantallParticipante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNumeroParticipante = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroEtapa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHorarioPartida = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtHorarioLlegada = new javax.swing.JTextField();
        btnEtapaSiguiente = new javax.swing.JButton();
        btnEtapaAnterior = new javax.swing.JButton();
        btnGuardarEtapa = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnParticipanteAnterior = new javax.swing.JButton();
        btnParticipanteSiguiente = new javax.swing.JButton();
        btnGuardarParticipante = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroPasajero = new javax.swing.JTextField();
        btnPasajeroSiguiente = new javax.swing.JButton();
        btnPasajeroAnterior = new javax.swing.JButton();
        btnGuardarPasajero = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Categoría");

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Camion", "Karting", "Moto" }));
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });

        jLabel3.setText("Matrícula");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Participante:");

        txtNumeroParticipante.setEditable(false);
        txtNumeroParticipante.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addGap(67, 67, 67)
                        .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNumeroParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Etapa:");

        txtNumeroEtapa.setEditable(false);
        txtNumeroEtapa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNumeroEtapa.setText("0");
        txtNumeroEtapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroEtapaActionPerformed(evt);
            }
        });

        jLabel8.setText("Horario de partida:");

        jLabel9.setText("Horario de llegada:");

        btnEtapaSiguiente.setText(">");
        btnEtapaSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtapaSiguienteActionPerformed(evt);
            }
        });

        btnEtapaAnterior.setText("<");
        btnEtapaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtapaAnteriorActionPerformed(evt);
            }
        });

        btnGuardarEtapa.setText("Guardar Etapa");
        btnGuardarEtapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEtapaActionPerformed(evt);
            }
        });

        btnParticipanteAnterior.setText("<");
        btnParticipanteAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParticipanteAnteriorActionPerformed(evt);
            }
        });

        btnParticipanteSiguiente.setText(">");
        btnParticipanteSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParticipanteSiguienteActionPerformed(evt);
            }
        });

        btnGuardarParticipante.setText("Guardar Participante");
        btnGuardarParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarParticipanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnEtapaAnterior)
                        .addGap(45, 45, 45)
                        .addComponent(btnGuardarEtapa)
                        .addGap(40, 40, 40)
                        .addComponent(btnEtapaSiguiente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroEtapa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHorarioPartida)
                            .addComponent(txtHorarioLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnParticipanteAnterior)
                .addGap(98, 98, 98)
                .addComponent(btnGuardarParticipante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnParticipanteSiguiente)
                .addGap(171, 171, 171))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNumeroEtapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtHorarioPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtHorarioLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEtapaAnterior)
                    .addComponent(btnGuardarEtapa)
                    .addComponent(btnEtapaSiguiente))
                .addGap(32, 32, 32)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnParticipanteAnterior)
                    .addComponent(btnParticipanteSiguiente)
                    .addComponent(btnGuardarParticipante))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.setText("Nombre y Apellido:");

        jLabel4.setText("DNI:");

        jLabel5.setText("Fecha de Nacimiento:");

        jLabel6.setText("Pasajero:");

        txtNumeroPasajero.setEditable(false);
        txtNumeroPasajero.setText("0");

        btnPasajeroSiguiente.setText(">");
        btnPasajeroSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasajeroSiguienteActionPerformed(evt);
            }
        });

        btnPasajeroAnterior.setText("<");
        btnPasajeroAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasajeroAnteriorActionPerformed(evt);
            }
        });

        btnGuardarPasajero.setText("Guardar Pasajero");
        btnGuardarPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPasajeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumeroPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnPasajeroAnterior)
                .addGap(55, 55, 55)
                .addComponent(btnGuardarPasajero)
                .addGap(53, 53, 53)
                .addComponent(btnPasajeroSiguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPasajeroAnterior)
                    .addComponent(btnGuardarPasajero)
                    .addComponent(btnPasajeroSiguiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNumeroPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroEtapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroEtapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroEtapaActionPerformed

    private void btnPasajeroSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasajeroSiguienteActionPerformed
        String numeroPasajero = txtNumeroPasajero.getText();
        int numero = Integer.parseInt(numeroPasajero);
        String categoria = (String) comboCategoria.getSelectedItem();

        if("Auto".equals(categoria) || "Camion".equals(categoria) ){
            if(numero < 3){
                numero = numero + 1;  
            }
        }
        if("Karting".equals(categoria)){
            if(numero < 1){
                numero = numero + 1;  
            }
        }
        numeroPasajero = String.valueOf(numero);
        txtNumeroPasajero.setText(numeroPasajero);
        // Datos pasajero
        //Pasajero pasajeroActual = pasajeros[numero];
        if (pasajeros[numero] != null){
            txtNombreApellido.setText(pasajeros[numero].getNombreApellido());
            txtDni.setText(pasajeros[numero].getDni());
            txtFechaNacimiento.setText(pasajeros[numero].getFechaNacimiento());
        }else{
            txtNombreApellido.setText(null);
            txtDni.setText(null);
            txtFechaNacimiento.setText(null);
        }
    }//GEN-LAST:event_btnPasajeroSiguienteActionPerformed

    private void btnPasajeroAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasajeroAnteriorActionPerformed
        String numeroPasajero = txtNumeroPasajero.getText();
        int numero = Integer.parseInt(numeroPasajero);
        if (numero > 0) {
            numero = numero - 1;
            numeroPasajero = String.valueOf(numero);
            txtNumeroPasajero.setText(numeroPasajero);
            // Datos pasajero
            if (pasajeros[numero] != null){
                txtNombreApellido.setText(pasajeros[numero].getNombreApellido());
                txtDni.setText(pasajeros[numero].getDni());
                txtFechaNacimiento.setText(pasajeros[numero].getFechaNacimiento());
            }else{
                txtNombreApellido.setText(null);
                txtDni.setText(null);
                txtFechaNacimiento.setText(null);
            }            
        }
    }//GEN-LAST:event_btnPasajeroAnteriorActionPerformed

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed
        txtNumeroPasajero.setText("0");// TODO add your handling code here:
    }//GEN-LAST:event_comboCategoriaActionPerformed

    private void btnEtapaSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtapaSiguienteActionPerformed
        String numeroEtapa = txtNumeroEtapa.getText();
        int numero = Integer.parseInt(numeroEtapa);
        if (numero < 2) {
            numero = numero + 1;
            numeroEtapa = String.valueOf(numero);
            txtNumeroEtapa.setText(numeroEtapa);
        }
        if(horarios[numero] != null){
            txtHorarioPartida.setText(horarios[numero].getPartida());
            txtHorarioLlegada.setText(horarios[numero].getLlegada());
        }else{
            txtHorarioPartida.setText("");
            txtHorarioLlegada.setText("");            
        }
    }//GEN-LAST:event_btnEtapaSiguienteActionPerformed

    private void btnEtapaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtapaAnteriorActionPerformed
        String numeroEtapa = txtNumeroEtapa.getText();
        int numero = Integer.parseInt(numeroEtapa);
        if (numero > 0) {
            numero = numero - 1;
            numeroEtapa = String.valueOf(numero);
            txtNumeroEtapa.setText(numeroEtapa);
        }
        if(horarios[numero] != null){
            txtHorarioPartida.setText(horarios[numero].getPartida());
            txtHorarioLlegada.setText(horarios[numero].getLlegada());
        }else{
            txtHorarioPartida.setText("");
            txtHorarioLlegada.setText("");            
        }
    }//GEN-LAST:event_btnEtapaAnteriorActionPerformed

    private void btnGuardarPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPasajeroActionPerformed
        String numeroPasajero = txtNumeroPasajero.getText();
        int numero = Integer.parseInt(numeroPasajero);      
        Pasajero pasajero = new Pasajero(txtNombreApellido.getText(),txtDni.getText(),txtFechaNacimiento.getText());
        pasajeros[numero] = pasajero;
    }//GEN-LAST:event_btnGuardarPasajeroActionPerformed

    private void btnParticipanteSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParticipanteSiguienteActionPerformed
        String numeroParticipante = txtNumeroParticipante.getText();
        int numero = Integer.parseInt(numeroParticipante);
        if (numero < 10) {
            numero = numero + 1;
            numeroParticipante = String.valueOf(numero);
            txtNumeroParticipante.setText(numeroParticipante);
        }
        if(participantes[numero] != null){
            Pasajero pasajeros[] = participantes[numero].getPasajeros();
            txtNombreApellido.setText(pasajeros[numero].getNombreApellido());
            txtDni.setText(pasajeros[numero].getDni());
            txtFechaNacimiento.setText(pasajeros[numero].getFechaNacimiento());
            txtMatricula.setText(participantes[numero].getMatricula());
            Horario horarios[] = participantes[numero].getHorarios();
            txtHorarioPartida.setText(horarios[numero].getPartida());
            txtHorarioLlegada.setText(horarios[numero].getLlegada());            
        }else{
            txtNombreApellido.setText(null);
            txtDni.setText(null);
            txtFechaNacimiento.setText(null);
            txtMatricula.setText(null);
            txtHorarioPartida.setText("");
            txtHorarioLlegada.setText("");
            }
     
    }//GEN-LAST:event_btnParticipanteSiguienteActionPerformed

    private void btnParticipanteAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParticipanteAnteriorActionPerformed
        String numeroParticipante = txtNumeroParticipante.getText();
        int numero = Integer.parseInt(numeroParticipante);
        if (numero > 0) {
            numero = numero - 1;
            numeroParticipante = String.valueOf(numero);
            txtNumeroParticipante.setText(numeroParticipante);
        }
        if(participantes[numero] != null){
            Pasajero pasajeros[] = participantes[numero].getPasajeros();
            txtNombreApellido.setText(pasajeros[numero].getNombreApellido());
            txtDni.setText(pasajeros[numero].getDni());
            txtFechaNacimiento.setText(pasajeros[numero].getFechaNacimiento());
            txtMatricula.setText(participantes[numero].getMatricula());
            Horario horarios[] = participantes[numero].getHorarios();
            txtHorarioPartida.setText(horarios[numero].getPartida());
            txtHorarioLlegada.setText(horarios[numero].getLlegada());            
        }else{
            txtNombreApellido.setText(null);
            txtDni.setText(null);
            txtFechaNacimiento.setText(null);
            txtMatricula.setText(null);
            txtHorarioPartida.setText("");
            txtHorarioLlegada.setText("");
            }        
    }//GEN-LAST:event_btnParticipanteAnteriorActionPerformed

    private void btnGuardarEtapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEtapaActionPerformed
        String numeroEtapa = txtNumeroEtapa.getText();
        int numero = Integer.parseInt(numeroEtapa);
        Horario horario = new Horario(txtHorarioPartida.getText(),txtHorarioLlegada.getText());
        horarios[numero] = horario;
    }//GEN-LAST:event_btnGuardarEtapaActionPerformed

    private void btnGuardarParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarParticipanteActionPerformed
        String numeroParticipante = txtNumeroParticipante.getText();
        int numero = Integer.parseInt(numeroParticipante);
        String categoria = (String) comboCategoria.getSelectedItem();
        Participante participante = new Participante(categoria,txtMatricula.getText(),numero,pasajeros,horarios);
        participantes[numero] = participante;
        
        for (Pasajero pasajero : pasajeros) {
            pasajero = null;
        }
        for (Horario horario : horarios) {
            horario = null;
        }
    }//GEN-LAST:event_btnGuardarParticipanteActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEtapaAnterior;
    private javax.swing.JButton btnEtapaSiguiente;
    private javax.swing.JButton btnGuardarEtapa;
    private javax.swing.JButton btnGuardarParticipante;
    private javax.swing.JButton btnGuardarPasajero;
    private javax.swing.JButton btnParticipanteAnterior;
    private javax.swing.JButton btnParticipanteSiguiente;
    private javax.swing.JButton btnPasajeroAnterior;
    private javax.swing.JButton btnPasajeroSiguiente;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtHorarioLlegada;
    private javax.swing.JTextField txtHorarioPartida;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombreApellido;
    private javax.swing.JTextField txtNumeroEtapa;
    private javax.swing.JTextField txtNumeroParticipante;
    private javax.swing.JTextField txtNumeroPasajero;
    // End of variables declaration//GEN-END:variables
}
